Many researchers have focused on determining the factors that have an impact on attitudes toward Mathematics. Some of these factors, such as gender, Mathematics anxiety, motivation, game preferences, grade level, extreme response style in test-taking, competence, enjoyment, perceived  relevance, mathematical thinking, race, and  prior mathematics achievement, can be categorized as components that are internal to the learner. The other elements, such as parental influences, teacher affective  support, classroom instruction, number type,classroom culture, teaching methods,school type, and risk-taking in class, are classified as factors that are external to the students. Among the internal constituents of attitudes toward Mathematics, gender is one of the most studied. 

### Gender 
students have a positive attitude toward mathematics. [@kar17; @mat12]  level  of attitudes  toward  mathematics  of  Grade  10  students  was  high [@jun19] 

males’ average attitude score was significantly less than females’ average attitude scores [@rec18] female  students scoring higher than  male students in both constructs (enjoyment of mathematics and mathematical self-perceptions)  [@afa18] Girl students reported more positive mathematics attitudes compared to boys when they experienced higher levels of autonomy in their mathematics classes.  [@zuo19]  Longitudinally, higher mathematical competence in sixth grade was associated with better mathematics attitudes in seventh grade for girls but not for boys. [@gea19] 

There is no significant difference between male and female students in terms of their attitude toward mathematics  [@kar17; @sar17; @sir19; @orm19]   No gender effect was identified although the girls showed a continuous decline in attitudes the further they progressed in school. [@mat12] 

<!-- 
there was a significant main effect of gender on mean attitude scores. males’ average attitude score was significantly less than females’ average attitude scores.   [@rec18] 
there was  a statistical significant  difference for gender in both constructs of the questionnaire, with female  students scoring higher than  male students in both constructs (enjoyment of mathematics and mathematical self-perceptions [@afa18] 
Longitudinally, higher mathematical competence in sixth grade was associated with lower mathematics anxiety for evaluations and better mathematics attitudes in seventh grade for girls but not for boys. The key finding is that adolescent girls’ mathematics anxiety and their attitudes toward mathematics are more reflective of their actual mathematical competence than they are for boys.  [@gea19] 
Girl students reported more positive mathematics attitudes compared to boys when they experienced higher levels of autonomy in their mathematics classes.  [@zuo19] 

students have a positive attitude toward mathematics. There is no significant difference between male and female students in terms of their attitude toward mathematics  [@kar17] 
no significant gender differences in either achievement or attitudes toward mathematics, [@sar17] 
As far as their genders are concerned, there are no differences between male and female students attitude toward mathematics.  [@sir19] 
no statistically  significant mean  difference  between  attitude  towards  mathematics  and metacognitive  skill scores  of  girls  and boys [@orm19] 
No gender effect was identified although the girls showed a continuous decline in attitudes the further they progressed in school. [@mat12] 


 -->

<!-- 
### gender 
Conclusion: there was a significant main effect of gender on mean attitude scores. males’ average attitude score was significantly less than females’ average attitude scores.   [@rec18] 
Problem: The purpose of this study was to investigate the relationship among seventh grade students’ mathematics self-efficacy, mathematics anx-iety, attitudes towards mathematics, mathematics achievement, gender and school type.
Participants: 934 seventh grade students with an average age of 12 from 13 elementary schools, seven public and six private, in Ankara, Turkey
Method: two-way ANOVAs, multiple regression analysis,  Two associational research types, causal-comparative and correlational research designs 
Notes/comments: good pattern for results reporting 
Weakness/recommendation: done in elementary, respondents sampled convenience

Conclusion: there was  a statistical significant  difference for gender in both constructs of the questionnaire, with female  students scoring higher than  male students in both constructs (enjoyment of mathematics and mathematical self-perceptions [@afa18] 
Problem: examined  the effect  of  gender on students’ attitudes towards Mathematics.
Participants: 1039 elementary  students from a Gulf  state
Method: structural  equation modelling,  confirmatory  factor analysis (CFA), multigroup CFA and  multiple indicators, multiple causes (MIMIC) modelling
Notes/comments: elementary 
Weakness/recommendation: 

Conclusion: students have a positive attitude toward mathematics. There is no significant difference between male and female students in terms of their attitude toward mathematics  [@kar17] 
Problem: investigates the attitude toward mathematics among the students enrolled in the Foundation Year Programme at Nazarbayev University
Participants: 108. There are 55 males, 53 females, 73 Mathematical-Physics (MP), 22 Biology-Chemistry (BC) and 13 International Relations-Economics (IRE) students.
Method: conducted quantitatively and an inventory developed by Tapia and Marsh II is adopted
Notes/comments: college 
Weakness/recommendation: 

Conclusion: no significant gender differences in either achievement or attitudes toward mathematics, [@sar17] 
Problem: investigate gender differences in students’ mathematics achievement and in their attitudes toward mathematics. 
Participants:  692 students (353 girls, 339 boys) between the ages of 12 and 16 years, enrolled in grades 7–9 at four private schools in Lebanon.
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: Longitudinally, higher mathematical competence in sixth grade was associated with lower mathematics anxiety for evaluations and better mathematics attitudes in seventh grade for girls but not for boys. The key finding is that adolescent girls’ mathematics anxiety and their attitudes toward mathematics are more reflective of their actual mathematical competence than they are for boys.  [@gea19] 
Problem: Sex differences in the strength of the relations between mathematics anxiety, mathematics attitudes, and mathematics achievement were assessed concurrently in sixth grade and longitudinally from sixth to seventh grade 
Participants: sixth grade (n = 1,091, 545 boys) and sixth to seventh grade (n = 190, 97 boys)
Method: 
Notes/comments: One implication is that relative to boys with low mathematics achievement, girls with low achievement are at higher risk of developing mathematics anxiety and poor attitudes toward mathematics
Weakness/recommendation: 

Conclusion: As far as their genders are concerned, there are no differences between male and female students attitude toward mathematics.  [@sir19] 
Problem: to analyze the students' attitude toward mathematics in terms of the different aspect of mathematics game preferences, grade levels, and genders.
Participants:  107 students. They were taken from 2 elementary schools and were taken through proportional random sampling
Method: used The Attitude Toward Mathematics Inventory (ATMI) 
Notes/comments: 
Weakness/recommendation: 

Conclusion: Girl students reported more positive mathematics attitudes compared to boys when they experienced higher levels of autonomy in their mathematics classes.  [@zuo19] 
Problem: investigate associations between such strategies (i.e., student autonomy, cooperation and teamwork, technology use, risk taking, and cognitively-demanding work) and students’ attitudes toward mathematics.
Participants: 
Method: hierarchical linear regression analyses 
Notes/comments: 
Weakness/recommendation: 

Conclusion: no statistically  significant mean  difference  between  attitude  towards  mathematics  and metacognitive  skill scores  of  girls  and boys [@orm19] 
Problem: analyze  the  effects  of  gender  and the  education  level  of  parents  on students’  attitudes  towards  mathematics  and meta cognitive  skills. analyze  the  relationship  between  previous  mathematics  grades  with  attitudes  towards  mathematics  and metacognition  skills
Participants: 122  students  from  different grades  in  middle  school  —  29  fifth  graders,  31 sixth  graders,  32  seventh  graders,  and  30  eighth  graders, middle  school  which  is  selected as  a  convenient sampling  methodology  in  the Melikgazi  district  of  Kayseri,  Turkey  during  the  fall semester  of  2018-2019  
Method: survey  model  within  quantitative  descriptive  studies.  Metacognition  Scale,  Attitude Scale,  and Demographics  Scale were administered  to  students  for  collecting  data.  Independent  samples  t-test,  oneway  analysis  of  varianc e (ANOVA),  and  Pearson  correlation  analysis  were run
Notes/comments: 
Weakness/recommendation: 

Conclusion: No gender effect was identified although the girls showed a continuous decline in attitudes the further they progressed in school. [@mat12] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 



Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 


### parental influences,  teacher  affective  support and  classroom  instruction
Conclusion: Students’  attitude  towards  mathematics  is  affected by  factors  such  as  parental influences,  teacher  affective  support and  classroom  instruction. Teacher  affective  support and classroom  instruction  predict  attitude  towards  mathematics  more  than  parental influences.  [@dav18] 
Problem: examine the inter-relationships  between these  factors  and  effects  on attitude  towards  mathematics
Participants: 318  Form  Four  students from  Sabah,  Malaysia
Method: partial least  squares-structural equation modeling approach
Notes/comments: 
Weakness/recommendation: 

Conclusion: Higher prior mathematics achievement and positive parental beliefs and attitudes were significant predictors of higher scores across the 3 indicators. At the classroom level, classroom assessment was significantly associated with less endorsement of all 3 indicators, higher levels of classroom modeling with greater endorsement of perceived usefulness of mathematics [@kiw17] 
Problem: investigated the effects of student and classroom characteristics on math self-confidence, perceived usefulness, and enjoyment of mathematics as multiple outcomes.
Participants: 7th-grade students from 78 classes of 49 schools 
Method: multivariate multilevel analysis 
Notes/comments: 
Weakness/recommendation: 

Conclusion: statistically significant positive  correlations  between  parents' and  students' attitudes toward  mathematics.  Additionally,  parents'  mathematics attitude significantly predicted students' attitudes toward mathematics [@moh17] 
Problem: investigate parents' attitudes toward mathematics, their students' attitude toward mathematics, and  the influence of  the  parents'  attitude on the  students' attitude toward  mathematics
Participants: n=146
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: adolescents  who perceived that their parents liked  mathematics and considered mathematics was  important for their children not only  to study but  also  for  their  career tended to  report higher levels  of intrinsic and instrumental motivation to learn mathematics, mathematics  self-concept and self-efficacy, and mathematics  work ethic [@are15] 
Problem: examined the relations of adolescent children's perceptions  of their parents' attitudes towards mathematics to their own attitudes  towards mathematics  and mathematics  achievement
Participants: 5116 adolescents from 384 schools  in the  United Arab Emirates
Method: cross-sectional study
Notes/comments: 
Weakness/recommendation: 

Students’  attitude  towards  mathematics  is  affected by  factors  such  as  parental influences,  teacher  affective  support and  classroom  instruction. Teacher  affective  support and classroom  instruction  predict  attitude  towards  mathematics  more  than  parental influences.  [@dav18] positive parental beliefs and attitudes were significant predictors of higher scores across math self-confidence, perceived usefulness, and enjoyment of mathematics [@kiw17] statistically significant positive  correlations  between  parents' and  students' attitudes toward  mathematics.  Additionally,  parents'  mathematics attitude significantly predicted students' attitudes toward mathematics [@moh17] adolescents  who perceived that their parents liked  mathematics and considered mathematics was  important for their children not only  to study but  also  for  their  career tended to  report higher levels  of intrinsic and instrumental motivation to learn mathematics, mathematics  self-concept and self-efficacy, and mathematics  work ethic [@are15] teachers and the social support of peers are also highly significant in understanding these attitudes. [@mat12]  

Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 


Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### Anxiety 
Conclusion: elementary students had higher level of attitude towards mathematics in comparison to their mathematics anxiety level. Findings of the study revealed that mathematics attitudes were linked to their mathematics anxiety. Although the magnitude of the correlations between mathematics anxiety and attitude towards mathematics were not very strong, the significant relationship between these two components should be acknowledged. [@hac17] 
Problem: examined the reciprocal relationship between anxiety and attitude towards mathematics in elementary students.
Participants: 310 fourth grade elementary students.
Method: 
Notes/comments: 
Weakness/recommendation:



Conclusion: negative correlation between mathematics anxiety and mathematics attitude  [@kar10] 
Problem: investigates the relationships between mathematics anxiety, attitudes toward mathematics and mathematical thinking among university students
Participants:  203 university students from the Faculty of Science, Engineering, Food Science, and Human Ecology in one of the public university in Malaysia.
Method:  60-item questionnaire included mathematical thinking rating scale, mathematics anxiety rating scale and mathematics attitudes rating scale. correlation analysis, independent t-test 
Notes/comments: good pattern for abstract 
Weakness/recommendation: 
 
Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 


Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

correlations between mathematics anxiety and attitude towards mathematics were not very strong but significant [@hac17]

negative correlation between mathematics anxiety and mathematics attitude  [@kar10] 


### motivational factors
Conclusion: intrinsic, home environment and teacher factors have positive direct effects on the students' attitudes toward mathematics with intrinsic factor having the strongest and the most significant effect on students' attitudes toward mathematics. The findings also revealed that  [@oye17] 
Problem: use path analysis to investigate the type of direct effects the motivational factors have on the students' attitudes toward mathematics.
Participants: twelve senior secondary schools were randomly selected from the Edo State South Senatorial District. Thirty students were randomly selected from each of the schools and a total of three hundred and sixty students were used for the study. 
Method: Pearson Moment correlation and Regression analysis 
Notes/comments: 
Weakness/recommendation: 



Conclusion: motivation-related variables are the main predictors of attitudes towards mathematics  [@mat12] 
Problem: understand how certain different but interrelated variables such as background, motivation, and social support could lead to an explanation of student attitudes towards math and to an understanding of the defining characteristics of these attitudes in the school environment. 
Participants: 1719 Portuguese students, from fifth-to-twelfth grade.
Method: Intrinsic Motivation Inventory, hierarchical analysis using structural equation modeling
Notes/comments: 
Weakness/recommendation: 


Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

intrinsic, home environment and teacher factors have positive direct effects on the students' attitudes toward mathematics with intrinsic factor having the strongest and the most significant effect on students' attitudes toward mathematics.[@oye17] motivation-related variables are the main predictors of attitudes towards mathematics compared to background and social support  [@mat12] 

### game preferences and grade levels

Conclusion: there are different students attitude toward mathematics based on their mathematics game preferences and their grade levels. [@sir19] 
Problem: to improve students’ attitudes towards learning mathematics by applying the Numbered Heads Together (NHT) cooperative learning method with a scientific approach
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### extreme response style
Conclusion: the extreme response style explains a significant amount of variances in the students’attitude toward mathematics. Additionally, students with a negative attitude toward mathematics were found to have an extreme response style. It was concluded that an extreme response style had an effect on students’ attitude [@dib19] 
Problem: explore how the extreme response style affects students’ attitudes towardmathematics of students
Participants: 15 countries were randomly selected among countries participated in TIMSS 2015
Method: both basic research and descriptive research, analyzed with the packages "lme4" and "irtrees" in R software
Notes/comments: 
Weakness/recommendation: 

### Number Type
Conclusion: children and adults have different attitudes about mathematics when asked specifically about whole numbers, as opposed to fractions. The vast majority of children and adults reported negative attitudes toward fractions despite having positive attitudes toward whole numbers. Across both children and adults, the difference in fraction and whole-number attitudes was present across levels of math achievement, indicating that it was not just participants who were worse at math whose attitudes differed by number type. [@sid19] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### competence,  enjoyment  and  perceived  relevance
Conclusion: competence,  enjoyment  and  perceived  relevance  significantly  related  to  attitude  and  that  competence  was  the  most  influential  factor  of  attitude [@bua19] 
Problem: a  new  conceptual  model  is  developed  based  on  van  Aalderen-Smeets  and  colleagues'  theoretical framework  of  teachers’  attitudes  to  explore  the  factors  that  affect  students’  attitude  toward  mathematics  in  vocational  education
Participants: 215  vocational  education  students
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: Longitudinally, higher mathematical competence in sixth grade was associated with better mathematics attitudes in seventh grade for girls but not for boys.  [@gea19] 
Problem: Sex differences in the strength of the relations between mathematics anxiety, mathematics attitudes, and mathematics achievement were assessed concurrently in sixth grade (n = 1,091, 545 boys) and longitudinally from sixth to seventh grade (n = 190, 97 boys).
Participants: 
Method: 
Notes/comments: girls with low achievement are at higher risk of developing mathematics anxiety and poor attitudes toward mathematics.
Weakness/recommendation: 


competence,  enjoyment  and  perceived  relevance are significantly  related  to  attitude  and  competence  was  the  most  influential  factor  of  attitude [@bua19] Longitudinally, higher mathematical competence in sixth grade was associated with better mathematics attitudes in seventh grade for girls but not for boys. [@gea19] 

### classroom  culture and teaching methods
Conclusion: statistically  significant  difference  in  the  significance  level  0.05  between  the  student-centered  group  and  the teacher-centered  group [@keu19] 
Problem: verify  the  relationship  between  the  students'  perception  of  the mathematics  classroom  culture  and  their    attitudes  toward  mathematics  learning
Participants: 253  sixth  grade  students
Method: questionnaire  survey  method, independent  sample  t-test 
Notes/comments: 
Weakness/recommendation: 

Conclusion: attitude towards the study of mathematics are a function of teachers teaching methods. Students exhibited a positive attitude when teachers’ use student centred strategies that motivate every student to put up his/her best. [@imo19] 
Problem: examines student attitude towards mathematics in Sagnerigu Municipality of Northern Region in Ghana, assess the perceptions of students learning in mathematics and its influence in their attitude towards mathematics
Participants: purposive sampling technique was used to select 180 Senior High School students in Sagnerigu Municipality of the Northern Region of Ghana. 
Method: Questionnaire
Notes/comments: 
Weakness/recommendation: 

statistically  significant  difference  between  the  student-centered  group  and  the teacher-centered  group [@keu19] Students exhibited a positive attitude when teachers’ use student centred strategies that motivate every student to put up his/her best. [@imo19] 

Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 



Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### mathematical thinking
Conclusion: significant high positive correlation exists between mathematical thinking and mathematics attitude [@kar10] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 


Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 



Conclusion: 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### school type
Conclusion: school type have significant effect on attitude scores. the attitude scores of private school stu-dents were significantly higher than the mean attitude scores of public school students. [@rec18] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

the attitude scores of private school stu-dents were significantly higher than the mean attitude scores of public school students. [@rec18] 

peer group factor and school environment factor have negative effects on students' attitudes toward mathematics [@oye17] 

The students enrolled in regular school programs show higher attitudes than those attending vocational programs. [@mum15] 

### risk-taking
Conclusion: higher levels of risk-taking in mathematics classes were associated with more positive mathematics attitudes for all students [@zuo19] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### race
Conclusion: African American students reported more positive mathematics attitudes compared to White students when they experienced higher levels of autonomy in their mathematics classes.  [@zuo19] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: Race and community background factors did not significantly affect the girls’ scores. [@deh15] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### prior mathematics achievement
Conclusion: Higher prior mathematics achievement was significant predictor of higher scores across math self-confidence, perceived usefulness, and enjoyment of mathematics [@kiw17] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: moderately  positive  relationship  was  found  between  the  students'  previous  year-end mathematics  scores  and their  attitude  towards  mathematics   [@orm19] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: positive correlation between previous high achievement in mathematics and favorable attitude toward it.  [@kar17] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

Higher prior mathematics achievement was significant predictor of higher scores across math self-confidence, perceived usefulness, and enjoyment of mathematics [@kiw17] positive correlation between previous high achievement in mathematics and favorable attitude toward it.  [@kar17] 

moderately  positive  relationship  was  found  between  the  students'  previous  year-end mathematics  scores  and their  attitude  towards  mathematics   [@orm19] 

 -->