Attitude is defined by psychologists as ``likes and dislikes -- favorable or unfavorable evaluations of and reactions to objects, people, situations, or other aspects of the world, including abstract ideas and social policies'' [@nol09]

Attitudes toward Mathematics have been defined as ``a  range  of  beliefs, relevance,  affections,  and  behaviors  regarding  such  matters as  a  person’s  belief  about  the  level  of  complexity  feature  of mathematics,  the  relevance  assigned  to  mathematics  for society,  feelings  of  interest  concerning  mathematics,  and  the desire  or  intention  to  learn  more  about  mathematics'' [@bua19]. Mathematics  attitude  should  be  viewed  as a predisposition to respond in an unfavorable or favorable way to mathematics. [@moe10]

Many researchers have discovered that attitudes toward Mathematics (ATM) predict math achievement [@dem19; @lip16; @pet19] although a few have determined that no  significant  relationship occurs between these two variables [@jun19]. In support of the findings by the majority of researchers in this field, @saa19 found out that when compared to students with negative attitudes toward mathematics, those who have very positive or moderately positive attitudes achieved higher scores in solving mathematical problems. This is because the differences in the students' attitudes affect how they select their strategies in problem solving and how they become mindful of assessing their solutions. 

Aside from Mathematics performance, attitudes have also been found to correlate with metacognition skill [@orm19] and self-efficacy perceptions towards mathematics [@mum15]. These studies reveal the importance of attitudes in learning Mathematics. In view of this, a deeper investigation of attitudes toward Mathematics and their underlying factors follows. 

<!-- Many researchers have discovered that attitudes toward Mathematics (ATM) predict math achievement [@dem19; @lip16; @pet19] although a few have determined that no  significant  relationship occurs between these two variables [@jun19]. In support of the findings by the majority of researchers in this field, @saa19 found out that when compared to students with negative attitudes toward mathematics, those who have very positive or moderately positive attitudes achieved higher scores in solving mathematical problems. This is because the differences in the students' attitudes affect how they select their strategies in problem solving and how they become mindful of assessing their solutions. 

Aside from Mathematics performance, attitudes have also been found to correlate with metacognition skill [@orm19] and self-efficacy perceptions towards mathematics [@mum15]. These studies reveal the importance of attitudes in learning Mathematics. In view of this, a deeper investigation of attitudes toward Mathematics and their underlying factors follows. 
 -->
 

 
<!-- 
Attitudes toward math (ATM) predict math achievement. [@dem19; @lip16; @pet19]  students with very positive or moderately positive levels of attitude performed better in comparison with students having negative attitudes toward mathematics [@saa19]
no  significant  relationship  of  attitudes  toward mathematics  with  mathematics  achievement [@jun19]
 students with different degrees of positive and negative attitudes toward mathematics showed meaningful differences in choosing the strategies and being aware of evaluating their solutions.[@saa19] 
 
 
 -->
 
<!-- 
### math achievement
Conclusion: Attitudes toward math (ATM) predict math achievement. Negative ATM are associated with avoidance of math content, while positive ATM are associated with exerting more effort on math tasks.  [@dem19]
Problem: This study investigated, for the first time, the effects of the interaction between math skill and ATM on the neurocognitive basis of arithmetic processing.
Participants: 9- to 12-year-old children
Method: 
Notes/comments: The results suggest that positive ATM in low-skill children might encourage them to more fully engage the neurocognitive systems underlying controlled effort and retrieval of multiplication facts. 
Weakness/recommendation: 

Conclusion: attitudes toward mathematics incrementally explaining 25% (Germany) and 7% (Belarus) of variance in mathematics grades over and above students' cognitive ability and Big Five personality dimensions.  [@lip16] 
Problem: investigated whether student-reported mathematics attitudes, conceptualized with the theory of planned behavior, incrementally contributed to students' mathematics grades over and above cognitive ability and the Big Five personality dimensions. 
Participants: College students from Germany (n = 179) and Belarus (n = 202) participated.
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: students with very positive or moderately positive levels of attitude performed better in comparison with students having negative attitudes toward mathematics, in all four stages of Polya’s problem-solving model, which includes understanding the problem, devising a plan, carrying out the plan, and looking back. students with different degrees of positive and negative attitudes toward mathematics showed meaningful differences in choosing the strategies and being aware of evaluating their solutions.[@saa19] 
Problem: investigate whether students’ attitudes toward mathematics can affect their learning to solve non-routine mathematical problems through a collaborative learning approach.
Participants: 214 students (grades 3–8) 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: students’  attitudes  have  a  significant  relationship with  their  achievement  in  mathematics [@pet19] 
Problem: determined  the  attitudes  and  academic  achievement  of  students who  are  recipients  of  Conditional Cash  Transfer  (CCT)  towards  mathematics  in  a  public  national  high  school,  Bohol,  Philippines
Participants: 112  respondents
Method: descriptive  research, Pearson  r, Attitudes  toward  Mathematics  Inventory  (ATMI) 
Notes/comments: local study 
Weakness/recommendation: 

Conclusion: no  significant  relationship  of  attitudes  toward mathematics  with  mathematics  achievement [@jun19] 
Problem: to  determine  the  level  of  attitudes  toward mathematics,  mathematics  self-efficacy,  mathematics  achievement and  the relationship  among  them
Participants: 200  of  Grade  10  students  who enrolled  in  A  Len  Bum  IDPs  High  School  in  the  academic  year  2018-2019,   in  Kachin  State,  Myanmar
Method: Attitudes toward  mathematics  questionnaire  (ATMQ)  and  sources  of  mathematics  self-efficacy scale  (SMSES)  
Notes/comments: 
Weakness/recommendation: 

Attitudes toward math (ATM) predict math achievement. [@dem19; @lip16; @pet19]  students with very positive or moderately positive levels of attitude performed better in comparison with students having negative attitudes toward mathematics [@saa19]
no  significant  relationship  of  attitudes  toward mathematics  with  mathematics  achievement [@jun19]
 students with different degrees of positive and negative attitudes toward mathematics showed meaningful differences in choosing the strategies and being aware of evaluating their solutions.[@saa19] 

### metacognition  skill
Conclusion: a  moderate  positive  relationship  was  found between  attitude  towards  mathematics  scores  and metacognition  skill  total  scores [@orm19] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### self-efficacy
Conclusion:  strong and positive correlation was found between students’ attitudes and self-efficacy perceptions towards mathematics. [@mum15] 
Problem: determine the students’ attitudes and self-efficacy perceptions towards mathematics in terms of education programs, gender, grade level and mathematics performance, it also aims to see the relationship between attitudes and self-efficacy perceptions towards mathematics themselves.
Participants:  212 students from different departments in a multi- program high school. 
Method:  İndependent t-test, one way ANOVA and correlation, descriptive
Notes/comments: 
Weakness/recommendation: 
 -->


<!-- 
Attitudes toward math (ATM) predict math achievement. [@dem19; @lip16; @pet19]  students with very positive or moderately positive levels of attitude performed better in comparison with students having negative attitudes toward mathematics [@saa19]
no  significant  relationship  of  attitudes  toward mathematics  with  mathematics  achievement [@jun19]
 students with different degrees of positive and negative attitudes toward mathematics showed meaningful differences in choosing the strategies and being aware of evaluating their solutions.[@saa19] 
 
 
 -->
 
<!-- 
### math achievement
Conclusion: Attitudes toward math (ATM) predict math achievement. Negative ATM are associated with avoidance of math content, while positive ATM are associated with exerting more effort on math tasks.  [@dem19]
Problem: This study investigated, for the first time, the effects of the interaction between math skill and ATM on the neurocognitive basis of arithmetic processing.
Participants: 9- to 12-year-old children
Method: 
Notes/comments: The results suggest that positive ATM in low-skill children might encourage them to more fully engage the neurocognitive systems underlying controlled effort and retrieval of multiplication facts. 
Weakness/recommendation: 

Conclusion: attitudes toward mathematics incrementally explaining 25% (Germany) and 7% (Belarus) of variance in mathematics grades over and above students' cognitive ability and Big Five personality dimensions.  [@lip16] 
Problem: investigated whether student-reported mathematics attitudes, conceptualized with the theory of planned behavior, incrementally contributed to students' mathematics grades over and above cognitive ability and the Big Five personality dimensions. 
Participants: College students from Germany (n = 179) and Belarus (n = 202) participated.
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: students with very positive or moderately positive levels of attitude performed better in comparison with students having negative attitudes toward mathematics, in all four stages of Polya’s problem-solving model, which includes understanding the problem, devising a plan, carrying out the plan, and looking back. students with different degrees of positive and negative attitudes toward mathematics showed meaningful differences in choosing the strategies and being aware of evaluating their solutions.[@saa19] 
Problem: investigate whether students’ attitudes toward mathematics can affect their learning to solve non-routine mathematical problems through a collaborative learning approach.
Participants: 214 students (grades 3–8) 
Method: 
Notes/comments: 
Weakness/recommendation: 

Conclusion: students’  attitudes  have  a  significant  relationship with  their  achievement  in  mathematics [@pet19] 
Problem: determined  the  attitudes  and  academic  achievement  of  students who  are  recipients  of  Conditional Cash  Transfer  (CCT)  towards  mathematics  in  a  public  national  high  school,  Bohol,  Philippines
Participants: 112  respondents
Method: descriptive  research, Pearson  r, Attitudes  toward  Mathematics  Inventory  (ATMI) 
Notes/comments: local study 
Weakness/recommendation: 

Conclusion: no  significant  relationship  of  attitudes  toward mathematics  with  mathematics  achievement [@jun19] 
Problem: to  determine  the  level  of  attitudes  toward mathematics,  mathematics  self-efficacy,  mathematics  achievement and  the relationship  among  them
Participants: 200  of  Grade  10  students  who enrolled  in  A  Len  Bum  IDPs  High  School  in  the  academic  year  2018-2019,   in  Kachin  State,  Myanmar
Method: Attitudes toward  mathematics  questionnaire  (ATMQ)  and  sources  of  mathematics  self-efficacy scale  (SMSES)  
Notes/comments: 
Weakness/recommendation: 

Attitudes toward math (ATM) predict math achievement. [@dem19; @lip16; @pet19]  students with very positive or moderately positive levels of attitude performed better in comparison with students having negative attitudes toward mathematics [@saa19]
no  significant  relationship  of  attitudes  toward mathematics  with  mathematics  achievement [@jun19]
 students with different degrees of positive and negative attitudes toward mathematics showed meaningful differences in choosing the strategies and being aware of evaluating their solutions.[@saa19] 

### metacognition  skill
Conclusion: a  moderate  positive  relationship  was  found between  attitude  towards  mathematics  scores  and metacognition  skill  total  scores [@orm19] 
Problem: 
Participants: 
Method: 
Notes/comments: 
Weakness/recommendation: 

### self-efficacy
Conclusion:  strong and positive correlation was found between students’ attitudes and self-efficacy perceptions towards mathematics. [@mum15] 
Problem: determine the students’ attitudes and self-efficacy perceptions towards mathematics in terms of education programs, gender, grade level and mathematics performance, it also aims to see the relationship between attitudes and self-efficacy perceptions towards mathematics themselves.
Participants:  212 students from different departments in a multi- program high school. 
Method:  İndependent t-test, one way ANOVA and correlation, descriptive
Notes/comments: 
Weakness/recommendation: 
 -->